package org.pp.objectstore.interfaces;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.FIELD)
/**
 * Mandatory unique id for object.
 * Applicable to only long field
 * @author prasantsmac
 *
 */
public @interface Id {
    /**
     * ID will be generated by default
     * @return
     */
	public boolean gen() default true;
}
